CREATE PUBLIC_USER_INFORMATION 		AS (SELECT * FROM keyholt.PUBLIC_USER_INFORMATION);
CREATE PUBLIC_ARE_FRIENDS 			AS (SELECT * FROM keyholt.PUBLIC_ARE_FRIENDS);
CREATE PUBLIC_PHOTO_INFORMATION 	AS (SELECT * FROM keyholt.PUBLIC_PHOTO_INFORMATION);
CREATE PUBLIC_TAG_INFORMATION 		AS (SELECT * FROM keyholt.PUBLIC_TAG_INFORMATION);
CREATE PUBLIC_EVENT_INFORMATION 	AS (SELECT * FROM keyholt.PUBLIC_EVENT_INFORMATION);