CREATE TABLE PUBLIC_USER_INFORMATION 		AS (SELECT * FROM keykholt.PUBLIC_USER_INFORMATION);
CREATE TABLE PUBLIC_ARE_FRIENDS 			AS (SELECT * FROM keyholt.PUBLIC_ARE_FRIENDS);
CREATE TABLE PUBLIC_PHOTO_INFORMATION 		AS (SELECT * FROM keyholt.PUBLIC_PHOTO_INFORMATION);
CREATE TABLE PUBLIC_TAG_INFORMATION 		AS (SELECT * FROM keyholt.PUBLIC_TAG_INFORMATION);
CREATE TABLE PUBLIC_EVENT_INFORMATION 		AS (SELECT * FROM keyholt.PUBLIC_EVENT_INFORMATION);