DROP TABLE TAGS;

DROP TABLE PHOTOS CASCADE CONSTRAINTS;
DROP TABLE ALBUMS CASCADE CONSTRAINTS;

DROP TABLE PARTICIPANTS;

DROP TABLE USER_EVENTS;

DROP TABLE EDUCATION;

DROP TRIGGER PROGRAMS_sequence_tirgger;
DROP SEQUENCE PROGRAMS_sequence;
DROP TABLE PROGRAMS;

DROP TABLE MESSAGE;

DROP TABLE USER_HOMETOWN_CITY;

DROP TABLE USER_CURRENT_CITY;

DROP TRIGGER CITIES_sequence_tirgger;
DROP SEQUENCE CITIES_sequence;
DROP TABLE CITIES;

DROP TRIGGER REPEAT_FRIENDS_CHECK;
DROP TABLE FRIENDS;

DROP TABLE USERS;
